---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# An evidence synthesis approach for combining different data sources on entomological efficacy of insecticides for indoor residual spraying 

| :loudspeaker:  Now published   |
|-----------------------------------------|

> [!IMPORTANT]
> [Green, N., Agossa, F., Yovogan, B., Oxborough, R., Kitau, J., Müller, P., Constant, E., Rowland, M., Tchacaya, E.F., Benjamin, K.G. and Churcher, T.S., 2022. An evidence synthesis approach for combining different data sources illustrated using entomological efficacy of insecticides for indoor residual spraying. PloS one, 17(3), p.e0263446.](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0263446)


#### Background
Malaria public health interventions are tested for entomological impact using experimental hut trials in different seasonal, ecological and endemic settings. In most but not all cases, data are collated as aggregated counts of potential outcomes from mosquito feeding attempts given the presence of an insecticidal intervention. Comprehensive data are more rarely available. These data can be appropriately combined to infer potential impact of vector control products across different settings over time.

#### Methods
Aggregated and comprehensive data from a meta-analysis of the impact of Actellic 300CS (Syngenta), an indoor residual spray (IRS) product, used on wall surfaces to kill mosquitoes and reduce malaria transmission, were analysed using a series of statistical models to understand the benefits and limitations of each. 

#### Results
Many more data are available in aggregated format (N = 23 datasets) relative to comprehensive format ($N$ = 3 datasets). The evidence synthesis model was able to predict the probability of mosquitoes dying or surviving and blood-feeding most robustly. Generating odds ratios from the correlated Bernoulli random sample indicates that when mortality and blood-feeding are positively correlated, as exhibited in our data, the number of successfully fed mosquitoes will be under-estimated. Analysis of either data set alone is problematic because aggregated data require making an assumption of independence and there are few and variable data in the comprehensive format.

#### Conclusions
We developed an approach to combine sources from expensive trials to maximise the inference that can be made from such data. Bayesian evidence synthesis enables inference from multiple datasets simultaneously to give a more informative result and highlight conflicts between sources. Advantages and limitations of these models are discussed. 
